[package]
name = "rtmp_stream_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rml_rtmp = "0.8.0"
